### ISSUE TITLE
BUG: nach Tot spawnt eine KI

### ISSUE THREAD

**Issue by synlos** [synlos/AltisLifeOnPrototype#27]
Nachdem ein Character stirbt wird eine KI gespawnt die den Namen und die ID des Spielers erhält. Diese kann wieder getötet werden und die Respawn Zeit verlängert sich.

**Comment by Blauschimmel** [comment]
Wir könnten ja einfach die Respawn Zeit auf die regulären 3 Sekunden setzen. Dann sollte man doch normal spawnen?

**Comment by Blauschimmel** [comment]
Könnte das damit zusammenhängen, dass im Editor der NPC, an dessen Position man auf der Insel seine 2 minuten abwarten würde, einfach nicht existiert?

**Comment by synlos** [comment]
Problem behoben. Lag an einem fehlenden marker "respawn_civilian"
https://community.bistudio.com/wiki/Arma_3_Respawn
