### ISSUE TITLE
Polizeiübungsgelände

### ISSUE THREAD

**Issue by synlos** [synlos/AltisLifeOnPrototype#8]
Entscheidung steht noch aus

**Comment by Blauschimmel** [comment]
Ich hab einen Prototypen fertiggestellt. Dieses Gelände ist essenziell für die Polizei Aus- und Weiterbildung sowie das Training. Diejenigen, die der Meinung sind, es gäbe nicht genug Platz, sollten sich mal etwas genauer mit der karte auseinandersetzen. Die Position, die ich gewählt habe, ist der Südzipfel von West Island und bedeckt dort nichtmal 1/10 der Fläche, da ich vieles auf das Wasser verlegt habe.
